# External gems
gems:
  - jekyll-archives
  - jekyll-sitemap

# Site settings
title: HJBoo Blog
subtitle: "Sharing is a good habit."
email: hjboo@qq.com
name: Bob
description: >
  I'm bob, a unity developer from china.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.hjboo.com" # the base hostname & protocol for your site
cover: "assets/images/eegj_antwan.jpg"
logo: "assets/images/logo/logo_180.png"

# Build settings
markdown: kramdown
paginate: 1
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: bencentra

# Google analytics
ga_tracking_id: "UA-55081307-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: thoughts
    desc: "Ramblings about things I've done, products I've used, and ideas I've encountered."

  - cat: code
    desc: "Snippets of useful code; tutorials, tips, and techniques."

  - cat: projects
    desc: "Highlights and updates of the cool things I do in my spare time."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: WeiXin
    icon: weixin
    username: WeiXin
    url: http://www.hjboo.com/wechat/
    desc: 我的微信
    share_url:
    share_title:
    share_link:

  - name: GitHub
    icon: github
    username: GitHub
    url: https://github.com/hjboo
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: QQ
    icon: qq
    username: QQ
    url: http://www.hjboo.com/qq/
    desc: 我的QQ
    share_url:
    share_title:
    share_link:

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/images/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/images/logo.png"

    os_repo: "https://github.com/bencentra/blog"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/blog.git"
